name: Sync any artifact from tenant

on:
  workflow_dispatch:
    inputs:
      packageId:
        description: 'Package ID'
        required: true
      directory:
        description: 'Target artifact directory (relative from Git repository root)'
        required: false
      includedIds:
        description: 'Included Ids (optional)'
        required: false
      excludedIds:
        description: 'Excluded Ids (optional)'
        required: false
      draft:
        description: 'Draft handling'
        type: choice
        options:
          - SKIP
          - ADD
          - ERROR
        required: false
      dirNaming:
        description: 'Naming convention for artifact directories'
        required: false
        type: choice
        options:
          - ID
          - NAME
      syncPackageDetails:
        description: "Sync package details"
        type: boolean
        required: false
      message:
        description: 'Commit message (optional)'
        required: false
jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:3.1.0

    steps:
    - uses: actions/checkout@v4

    - name: 'Sync any artifact'
      uses: SAP/project-piper-action@master
      with:
        tmn-host: ab8ecbdetrial.hana.ondemand.com
        oauth-host: ab8ecbdetrial.authentication.eu10.hana.ondemand.com
        oauth-clientid: ${{ secrets.DEV_CLIENT_ID }}
        oauth-clientsecret: ${{ secrets.DEV_CLIENT_SECRET }}
        package-id: ${{ github.event.inputs.packageId }}
        dir-artifacts-relative: ${{ github.event.inputs.directory }}
        dir-naming-type: ${{ github.event.inputs.dirNaming }}
        draft-handling: ${{ github.event.inputs.draft }}
        ids-include: ${{ github.event.inputs.includedIds }}
        ids-exclude: ${{ github.event.inputs.excludedIds }}
        git-commit-msg: ${{ github.event.inputs.message }}
        sync-package-details: ${{ github.event.inputs.syncPackageDetails }}
        piper-version: latest
        command: githubPublishRelease
